POST https://skinsight-server-app-dmn2lplbqq-et.a.run.app/api/v1/auth/login
Content-Type: application/json

{
    "username": "root",
    "password": "root"
}

###
GET http://localhost:8000/api/v1/auth/verify
Authorization: Bearer Token in here

###
POST https://skinsight-server-app-dmn2lplbqq-et.a.run.app/api/v1/auth/register
Content-Type: application/json

{
    "name":"a",
    "gender":"male",
    "birthday":"a",
    "birthplace":"a",
    "address":"a",
    "email":"aa",
    "username":"aaaaa",
    "password":"aaaa"
}

###
GET http://localhost:8000/api/v1/histories
Authorization: Bearer Token in here

###
POST http://localhost:8000/api/v1/histories/create
Authorization: Bearer Token in here
Content-Type: application/json

{
    "prediction_age":40,
    "prediction_result":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia repudiandae ratione, molestias ad omnis doloremque aut numquam cum aliquid magni iure consectetur laborum ipsam et exercitationem voluptate provident quae beatae."
}

###
POST http://localhost:8000/api/v1/faces/predict
Authorization: Bearer Token in here
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="pexels-simon-robben-614810.jpg"
Content-Type: image/jpeg

(data)
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET http://localhost:8000/api/v1/users/profile
Authorization: Bearer Token in here