POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "username": "root",
    "password": "root"
}

###
GET http://localhost:8000/api/v1/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkRldmVsb3BlciIsImlhdCI6MTY4NjMyNjcwMCwiZXhwIjoxNjkxNTEwNzAwfQ.SHzjXsNYb9wlIMCZ1iJkbd5ofiNX--YprLVA6eivxVs

###
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
    "name":"a",
    "gender":"male",
    "birthday":"a",
    "birthplace":"a",
    "address":"a",
    "email":"a",
    "username":"aaaa",
    "password":"aaaa"
}

###
POST http://localhost:8000/api/v1/history/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkRldmVsb3BlciIsImlhdCI6MTY4NjMyNjcwMCwiZXhwIjoxNjkxNTEwNzAwfQ.SHzjXsNYb9wlIMCZ1iJkbd5ofiNX--YprLVA6eivxVsa
Content-Type: application/json

{
    "prediction_age":40,
    "prediction_result":"test"
}